name: Python CI/CD with Docker

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: german-credit-app

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Python environment
    - name: Setup Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # 3️⃣ Install dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ Run pytest
    - name: Run Python tests
      run: |
        # Add project root to PYTHONPATH to resolve imports
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/ --maxfail=1 --disable-warnings -q

    # 5️⃣ Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

    # 7️⃣ Push Docker image to DockerHub
    - name: Push Docker image
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
